### ISSUE TITLE
How to run???

### ISSUE THREAD

**Issue by byaka** [alun/as3-proxy#1]
Ubuntu 14.04

```
$ sbt run
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Getting org.scala-sbt sbt 0.13.8 ...
...
[info] Done updating.
[info] Compiling 1 Scala source to /home/byaka/Загрузки/as3-proxy-master/target/scala-2.10/classes...
[info] Running SwfTool 

  Usage: SwfTool$ file.swf {proxify, mainClass, dump}

  Where:
    file.swf - path to file you want work with

    proxify - make an addEventListener proxied version of the swf
    mainClass - print a mainclass name
    dump - prints bytecode dump on the screen
[success] Total time: 24 s, completed 27.06.2015 15:04:04
```

And what now?

**Comment by alun** [comment]
This is program usage printed on the screen - there are three modes available - dump, mainClass and proxify.

I've added some more command line samples and test SWF file into repository, please see the project's README file. And don't forget to do a fresh pull, as it was necessary to switch to Scala 2.8.1.

**Comment by byaka** [comment]
[**@alun**](https://github.com/alun) commented on [27 июня 2015 г., 16:25 GMT+3](https://github.com/alun/as3-proxy/issues/1#issuecomment-116047344):

> This is program usage printed on the screen - there are three modes available - dump, mainClass and proxify.
> 
> I've added some more command line samples and test SWF file into repository, please see the project's README file. And don't forget to do a fresh pull, as it was necessary to switch to Scala 2.8.1.

Thx **alan** !
